---
title: "Proyecto Final Procesamiento de datos"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
runtime: shiny    
---

```{r carga de paquetes, message=FALSE, warning=FALSE}
library(flexdashboard)
library(dplyr) 
library(sf) 
library(DT) 
library(plotly) 
library(leaflet) 
library(raster) 
library(ggplot2) 
library(rgdal)
library(tidyverse)
library(stringi)
library(ggthemes)
library(lubridate)
library(shiny)
```

```{r carga-de-datos, message=FALSE, warning=FALSE}
delitos <-
  readxl::read_excel(path = "estadisticaspoliciales2021.xls")
distritos <-
  st_read(
    dsn = "distritos_simplificados.geojson",
    quiet = TRUE
  ) %>%
  st_transform(4326)
```

```{r Union-de-datos-cantones, message=FALSE, warning=FALSE}
distritos <-
  distritos %>%
  mutate(canton_normalizado = tolower(stri_trans_general(canton, id = "Latin-ASCII")))

delitos <-
  delitos %>%
  mutate(canton_normalizado = tolower(stri_trans_general(Canton, id = "Latin-ASCII")))

delitos <-
  delitos %>%
  mutate(Canton = if_else(Canton == "LEON CORTES", "LEON CORTES CASTRO", Canton)) %>%
  mutate(Canton = if_else(Canton == "VASQUEZ DE CORONADO", "VAZQUEZ DE CORONADO", Canton))

delitos <-
  delitos %>%
  mutate(canton_normalizado = tolower(stri_trans_general(Canton, id = "Latin-ASCII")))

delitos <-
  delitos %>%
  left_join(
    dplyr::select(
      st_drop_geometry(distritos),
      cod_canton,
      canton_normalizado
    ),
    by = "canton_normalizado",
    copy = FALSE,
    keep = FALSE
  )
```

```{r Union-de-datos-distritos, message=FALSE, warning=FALSE}
distritos <-
  distritos %>%
  mutate(distrito_normalizado = tolower(stri_trans_general(distrito, id = "Latin-ASCII")))

delitos <-
  delitos %>%
  mutate(distrito_normalizado = tolower(stri_trans_general(Distrito, id = "Latin-ASCII")))

delitos <-
  delitos %>%
  mutate(Distrito = if_else(cod_canton == 703 & Distrito == "CAIRO", "EL CAIRO", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 210 & Distrito == "FORTUNA", "LA FORTUNA", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 410 & Distrito == "HORQUETAS", "LAS HORQUETAS", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 119 & Distrito == "GENERAL", "EL GENERAL", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 402 & Distrito == "SAN JOSE DE LA MONTA?A", "SAN JOSE DE LA MONTANA", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 602 & Distrito == "MACACOMA", "MACACONA", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 301 & Distrito == "SAN FRANCISCO", "AGUACALIENTE O SAN FRANCISCO", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 209 & Distrito == "CEIBA", "LA CEIBA", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 605 & Distrito == "CORTES", "PUERTO CORTES", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 201 & Distrito == "LA GARITA", "GARITA", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 119 & Distrito == "LA AMISTAD", "LA  AMISTAD", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 213 & Distrito == "SAN JOSE (PIZOTE)", "SAN JOSE O PIZOTE", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 607 & Distrito == "JIMENEZ", "PUERTO JIMENEZ", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 405 & Distrito == "LOS ANGELES", "ANGELES", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 301 & Distrito == "GUADALUPE", "GUADALUPE O ARENILLA", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 407 & Distrito == "ASUNCION", "LA ASUNCION", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 209 & Distrito == "MASTATE", "EL MASTATE", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 604 & Distrito == "UNION", "LA UNION", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 108 & Distrito == "MATA PLATANO", "MATA DE PLATANO", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 608 & Distrito == "AGUA BUENA", "AGUABUENA", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 206 & Distrito == "ROSARIO", "EL ROSARIO", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 210 & Distrito == "PALMERA", "LA PALMERA", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 210 & Distrito == "TIGRA", "LA TIGRA", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 706 & Distrito == "MERECEDES", "MERCEDES", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 504 & Distrito == "FORTUNA", "LA FORTUNA", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 605 & Distrito == "DRAKE", "BAHIA DRAKE", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 207 & Distrito == "GRANJA", "LA GRANJA", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 410 & Distrito == "CURE?A", "CURENA", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 305 & Distrito == "EL CHIRRIPO", "CHIRRIPO", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 106 & Distrito == "LA LEGUA", "LEGUA", Distrito)) %>%
  mutate(Distrito = if_else(cod_canton == 211 & Distrito == "TAPEZCO", "TAPESCO", Distrito))
  
delitos <-
  delitos %>%
  mutate(distrito_normalizado = tolower(stri_trans_general(Distrito, id = "Latin-ASCII")))

delitos <-
  delitos %>%
  left_join(
    dplyr::select(
      st_drop_geometry(distritos),
      codigo_dta,
      cod_canton,
      distrito_normalizado
    ),
    by = c("cod_canton" = "cod_canton", "distrito_normalizado" = "distrito_normalizado"),
    copy = FALSE,
    keep = FALSE
  )

delitos_x_distrito <-
  delitos %>%
  count(codigo_dta, name = "delitos")

distritos_delitos <-
  distritos %>%
  left_join(
    delitos_x_distrito,
    by = "codigo_dta",
    copy = FALSE,
    keep = FALSE
  ) %>%
  mutate(delitos = ifelse(is.na(delitos), 0, delitos))
```

```{r lista-delito}

lista_Delito <- unique(delitos$Delito)
lista_Delito <- sort(lista_Delito)
lista_Delito <- c("Todos", lista_Delito)
```

```{r lista-victima}

lista_Victima <- unique(delitos$Victima)
lista_Victima <- sort(lista_Victima)
lista_Victima <- c("Todas", lista_Victima)
```

```{r lista-genero}

lista_Genero <- unique(delitos$Genero)
lista_Genero <- sort(lista_Genero)
lista_Genero <- c("Todos", lista_Genero)
```

```{r lista-edad}

lista_Edad <- unique(delitos$Edad)
lista_Edad <- sort(lista_Edad)
lista_Edad <- c("Todas", lista_Edad)
```

Mapa y Tabla
=======================================================================

Row {data-height=5}
-----------------------------------------------------------------------

### **Fuente de los datos: [Instituto Geográfico Nacional (IGN)](https://www.snitcr.go.cr/ico_servicios_ogc_info?k=bm9kbzo6MjY=&nombre=IGN%20Cartograf%C3%ADa%201:5mil)**
### **Fuente de los datos: [Organismo de Investigación Juficial (OIJ)](https://sitiooij.poder-judicial.go.cr/index.php/ayuda/servicios-policiales/servicios-a-organizaciones/indice-de-transparencia-del-sector-publico-costarricense/datos-abiertos)**

Column {.sidebar}
-------------------------------------

```{r filtros}
h3("Filtros de datos:")  

selectInput(
  inputId = "Delitos",
  label = "Delito",
  choices = lista_Delito,
  selected = "Todos"
)  

selectInput(
  inputId = "Victima",
  label = "Víctima",
  choices = lista_Victima,
  selected = "Todas"
)  

selectInput(
  inputId = "Genero",
  label = "Género",
  choices = lista_Genero,
  selected = "Todos"
)  

selectInput(
  inputId = "Edad",
  label = "Edad",
  choices = lista_Edad,
  selected = "Todas"
)  

filtrarDelitos <- reactive({
  
  delitos_filtrados <- delitos
  
    if (input$Delitos != "Todos") {
    delitos_filtrados <-
      delitos %>%
      filter(Delito == input$Delitos)
  }  
  
  if (input$Victima != "Todas") {
    delitos_filtrados <-
      delitos %>%
      filter(Victima == input$Victima)
  }  
  
  if (input$Genero != "Todos") {
    delitos_filtrados <-
      delitos %>%
      filter(Genero == input$Genero)
  } 
  
  if (input$Edad != "Todas") {
    delitos_filtrados <-
      delitos %>%
      filter(Edad == input$Edad)
  } 
  
  return(delitos_filtrados)
})
```

Column 
-------------------------------------

### Mapa {data-width=350}

```{r mapa-coropletas, echo=FALSE, warning=FALSE}

colores_distritos_delitos <-
  colorNumeric(palette = "Set2",
               domain = distritos_delitos$delitos,
               na.color = "transparent")
renderLeaflet({
  delitos <- filtrarDelitos()

delitos_x_distrito <-
  delitos %>%
  count(codigo_dta, name = "delitos")

distritos_delitos <-
  distritos %>%
  left_join(
    delitos_x_distrito,
    by = "codigo_dta",
    copy = FALSE,
    keep = FALSE
  ) %>%
  mutate(delitos = ifelse(is.na(delitos), 0, delitos)) 

leaflet() %>%
  setView(
    lng = -84.19452,
    lat = 9.572735,
    zoom = 7,2) %>%
  addTiles(group = "OpenStreetMap") %>%
  addPolygons(
    data = distritos_delitos,
    fillColor = ~ colores_distritos_delitos(distritos_delitos$delitos),
    fillOpacity = 0.8,
    color = "black",
    stroke = TRUE,
    weight = 1.0,
    popup = paste(
      paste(
        "Provincia:",
        distritos_delitos$provincia
      ), 
      paste(
        "Cantón:",
        distritos_delitos$canton
      ), 
      paste(
        "Distrito:",
        distritos_delitos$distrito
      ), 
      paste(
        "Delitos:",
        distritos_delitos$delitos
      ), 
      sep = "<br>"
    ), 
    group = "Delitos en distritos"
  ) %>%
  addLayersControl(
    baseGroups = c("OpenStreetMap"),
    overlayGroups = c("Delitos en distritos")
  ) %>%
  addLegend(
    position = "bottomleft",
    pal = colores_distritos_delitos,
    values = distritos_delitos$delitos,
    group = "Delitos en distritos",
    title = "Cantidad de delitos"
  )
})
```

### Tabla {data-width=650}

```{r Tabla, echo=FALSE, warning=FALSE}
renderDT({
  delitos <- filtrarDelitos()
  
delitos %>%
  dplyr::select(Delito,
                Fecha,
                Victima,
                Edad,
                Genero,
                Provincia,
                Canton,
                Distrito) %>%
  mutate(Fecha = as.Date(Fecha, format = "%d/%m/%Y")) %>%
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    ),
    colnames = c(
      "Delito",
      "Fecha",
      "Víctima",
      "Edad",
      "Género",
      "Provincia",
      "Cantón",
      "Distrito"
    )
  )
})
```

Gráficos
=======================================================================

Row
----------------------------------------------------------------------

### Gráfico 1

```{r gráfico-barras-1, echo=FALSE, warning=FALSE}
renderPlotly({
  delitos <- filtrarDelitos()
  
Cantidad_de_delito_por_delito <-
  delitos %>%
  count(Delito) %>%
  ggplot(aes(x = reorder(Delito, n), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Cantidad de delitos por tipo de delito") +
  xlab("Tipo de Delito") +
  ylab("Cantidad") +
  coord_flip() +
  theme_hc()

ggplotly(Cantidad_de_delito_por_delito) %>% config(locale = 'es')
})
```

### Gráfico 2

```{r gráfico-barras-2, echo=FALSE, warning=FALSE}
renderPlotly({
  delitos <- filtrarDelitos()
  
Cantidad_de_delito_por_victima <-
  delitos %>%
  count(Victima) %>%
  ggplot(aes(x = reorder(Victima, -n), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Cantidad de delitos por tipo de víctima") +
  xlab("Tipo de Víctima") +
  ylab("Cantidad") +
  theme_hc()

ggplotly(Cantidad_de_delito_por_victima) %>% config(locale = 'es')
})
```

Row
-----------------------------------------------------------------------

### Gráfico 3

```{r gráfico-barras-3, echo=FALSE, warning=FALSE}
renderPlotly({
  delitos <- filtrarDelitos()
  
Proporcion_por_genero <-
  delitos %>%
  ggplot(aes(x = Delito, fill = Genero)) +
  geom_bar(position = "fill",) +
  ggtitle("Proporciones de género") +
  xlab("Delito") +
  ylab("Proporción") +
  labs(fill = "Género") +
  coord_flip() +
  theme_minimal()

ggplotly(Proporcion_por_genero) %>% config(locale = 'es')
})
```

### Gráfico 4

```{r gráfico-barras-4, echo=FALSE, warning=FALSE}
renderPlotly({
  delitos <- filtrarDelitos()
  
delitos$Mes <- month(delitos$Fecha, label = TRUE)
Cantidad_de_delitos_por_mes <-
  ggplot(data= delitos, aes(x = Mes)) +
  geom_bar(, fill = "RoyalBlue2") +
  ggtitle("Cantidad de delitos por mes") +
  xlab("Meses") +
  ylab("Cantidad de Delitos") +
  theme_hc()

ggplotly(Cantidad_de_delitos_por_mes) %>% config(locale = 'es')
})
```

### Gráfico 5

```{r gráfico-barras-5, echo=FALSE, warning=FALSE}
renderPlotly({
  delitos <- filtrarDelitos()
  
Proporcion_de_edad_por_delito <-
  delitos %>%
  ggplot(aes(x = Delito, fill = Edad)) +
  geom_bar(position = "fill") +
  ggtitle("Cantidad de delitos por edad") +
  xlab("Delito") +
  ylab("Proporción") +
  labs(fill = "Edad") +
  coord_flip() +
  theme_minimal()

ggplotly(Proporcion_de_edad_por_delito) %>% config(locale = 'es')
})
```